### PR TITLE
use gradle-docker plugin for docker builds

### PR DESCRIPTION
**Pull request by sherzberg**
this change allows you to build the docker image from gradle. this makes it easier to get images built and also limits the amount of code needed to get a container built.

I also removed the apt caching and moved the wget of the kafka distribution to utilize docker caching.

### CODE REVIEW

**Comment by sherzberg** [comment]
Just rebased this off master and also fixed an issue when there are multiple versions of the jar built in the `out/` folder.

**Comment by dmitrypekar** [comment]
Sorry, but I think that leaving .Dockerfile standalone would be more convenient to docker users.
Most likely that they are familiar with .Dockerfile syntax, than gradle-docker syntax. 

But I'll port some other changes from with PR (for instance changes in DOCKER.md).

**Comment by sherzberg** [comment]
Ok. The main reason I wanted to change this was so there was no build script like their is currently in master. Have thoughts on if we can get rid of that?

The second reason was to utilize docker caching for downloading and managing versions for the kafka binaries. Thoughts on just putting that in the Dockerfile?

**Comment by dmitrypekar** [comment]
Let it be a build script. I see no big disadvantages of that.

Regarding caching. For now it would not download same kafka binaries (-nc option).

**Comment by dmitrypekar** [comment]
Closing this now.

**Pull request closed without merging**
