### PR TITLE
Fix snappy support 

### PR DESCRIPTION
**Pull request by sargun**

### CODE REVIEW

**Comment by sargun** [comment]
This is a short-term work around to fixing the class loader that we're using in BrokerServer. Right now, including the snappy jar in the actual executor works around the problem.

**Comment by sargun** [comment]
Related to #147

**Comment by dmitrypekar** [comment]
hi @sargun 
Thanks for a PR, but let's wait a little bit. May be, I would be able to provide a normal solution.
For now I can't reproduce the problem locally. Snappy jar seems to be loaded fine. Need to request additional info about the issue.

**Comment by sargun** [comment]
@dmitrypekar I can reproduce the issue locally. I'm using JVM 1.7.0_85. It seems like if you have the Snappy Java libraries installed on your system it works okay, but if you don't, it tries to load them from the JAR, which fails.

**Comment by DarinJ** [comment]
@sargun I attempted this fix and it didn't help, I was optimistic as the native libs were statically compiled, I'm glad to hear the behavior can be reproduced though.

**Comment by dmitrypekar** [comment]
Applied this fix - https://github.com/mesos/kafka/pull/158
Closing this PR.

**Pull request closed without merging**
