### PR TITLE
Docker Cleanup

### PR DESCRIPTION
**Pull request by nicgrayson**
1. sudo should only be used on docker commands if needed
2. COPY requires the directories to exist. I think this complicates the Dockerfile with no real benefit.

Let me know if you have any questions.

### CODE REVIEW

**Comment by sherzberg** [comment]
I haven't seen any Dockerfiles with caching like this. Curious if it would be better to do this caching outside the Dockefile would be best?

Maybe something like? https://github.com/jpetazzo/squid-in-a-can This would help maintainers and maybe make contributors feel more familiar?

**Comment by nicgrayson** [comment]
1. sudo doesn't work on a mac with boot2docker. This a why using just a Dockerfile and not a shell script to run docker is a great idea.
2. COPY requires the directories to exist

**Comment by dmitrypekar** [comment]
@nicgrayson 
1. It's clear now, thank you for clarification. Will incorporate your commit with skipping sudo;
2. This command `COPY .docker/apt-proxy* /tmp/apt-proxy` doesn't require directory/file to exist, so should work without existing apt-proxy file.

**Comment by dmitrypekar** [comment]
@nicgrayson Merged your patch that skips sudo for docker. I guess this PR could be closed for now?

**Comment by dmitrypekar** [comment]
@sherzberg Thanks for the point. Need to think about that. But probably the changes would not be in the scope of the current PR.

**Pull request closed without merging**
