### PR TITLE
Upgrade Mesos to 0.28 and add support for multi-disk volumes

### PR DESCRIPTION
**Pull request by ryaminal**
- use jdk docker image base

### CODE REVIEW

**Comment by ryaminal** [comment]
This contains an upgrade of mesos which is a dependency for multi-disk volume support which we have implemented here https://github.com/vivint-smarthome/kafka-mesos/commit/4b9f45eda2118e2fcf790a5802d91949956efab9

Support for multi-disk resources added some time around Mesos `0.27.0`.

**Comment by timcharper** [comment]
We noticed that an attempt to upgrade Kafka was elsewhere declined, so we removed those changes from this changeset.

This change targets Mesos 0.28.x and adds support for multi-disk resources (IE mount disk volumes).

**Comment by cliff-ops** [comment]
it looks like this would fix issue 226 correct?

**Comment by timcharper** [comment]
Yessir.

resolves https://github.com/mesos/kafka/issues/226

**Comment by cliff-ops** [comment]
Awesome! Nice work. Do you know any reason its not being merged? I see others having the same issues.

**Comment by timcharper** [comment]
I wish I could say, @cliff-ops. Seems like the maintainers are pretty choosy and short on time.

**Pull request merged**
